root = "."
tmp_dir = "bin"

[build]
  bin = "./bin/api"
  cmd = "go build -o ./bin/api ./cmd/api"
  delay = 1000
  exclude_dir = ["bin", "deployments", "output"]
  exclude_file = []
  exclude_regex = ["_test.go", "_templ.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  kill_delay = "0.3s"
  log = "build-errors.log"
  send_interrupt = true
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = true